version: 2
jobs:
  build:
    working_directory: ~/message-wall
    docker:
      - image: node:10.6
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: npm install
          command: npm config set registry http://registry.npmjs.org/;npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
